# Generated by Django 2.1.2 on 2018-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='is_internal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
