# Generated by Django 2.1.2 on 2018-11-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0002_auto_20181027_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scm_login',
            field=models.ForeignKey(blank=True, help_text='... or leave this blank and add an SSH key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='vespene.ServiceLogin'),
        ),
        migrations.AlterField(
            model_name='workerpool',
            name='sudo_password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
