# Generated by Django 2.1.2 on 2018-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0003_auto_20181101_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpool',
            name='autoscaling_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='autoscaling_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='excess',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='executor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='executor_command',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='last_autoscaled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='maximum',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='minimum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='multiplier',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='planner',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='queued_weight',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='reevaluate_minutes',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='workerpool',
            name='running_weight',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
