# Generated by Django 2.1.2 on 2018-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0004_auto_20181105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpool',
            name='queued_weight',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='workerpool',
            name='running_weight',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
