# Generated by Django 2.1.2 on 2018-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0005_auto_20181105_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpool',
            name='multiplier',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
