# Generated by Django 2.1.2 on 2018-11-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0006_auto_20181105_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recursive',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
