# Generated by Django 2.1.2 on 2018-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0007_project_recursive'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipeline',
            name='pipeline_group_name_idx',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='group_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='allow_pipeline_definition',
            field=models.BooleanField(default=True),
        ),
    ]
