# Generated by Django 2.1.2 on 2018-12-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespene', '0008_auto_20181106_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerpool',
            name='sudo_password',
        ),
    ]
